---
- name: ":ruby:Ruby 2.7 on :ubuntu:ubuntu18.04"
  command: docker build -f ./2.7/ubuntu18.04/Dockerfile .
- name: ":ruby:Ruby 2.7 on :ubuntu:ubuntu16.04"
  command: docker build -f ./2.7/ubuntu16.04/Dockerfile .
- name: ":ruby:Ruby 2.7 on :ubuntu:ubuntu14.04"
  command: docker build -f ./2.7/ubuntu14.04/Dockerfile .
- name: ":ruby:Ruby 2.6 on :ubuntu:ubuntu18.04"
  command: docker build -f ./2.6/ubuntu18.04/Dockerfile .
- name: ":ruby:Ruby 2.6 on :ubuntu:ubuntu16.04"
  command: docker build -f ./2.6/ubuntu16.04/Dockerfile .
- name: ":ruby:Ruby 2.6 on :ubuntu:ubuntu14.04"
  command: docker build -f ./2.6/ubuntu14.04/Dockerfile .
- name: ":ruby:Ruby 2.4 on :ubuntu:ubuntu18.04"
  command: docker build -f ./2.4/ubuntu18.04/Dockerfile .
- name: ":ruby:Ruby 2.4 on :ubuntu:ubuntu16.04"
  command: docker build -f ./2.4/ubuntu16.04/Dockerfile .
- name: ":ruby:Ruby 2.4 on :ubuntu:ubuntu14.04"
  command: docker build -f ./2.4/ubuntu14.04/Dockerfile .
- name: ":ruby:Ruby 2.3 on :ubuntu:ubuntu18.04"
  command: docker build -f ./2.3/ubuntu18.04/Dockerfile .
- name: ":ruby:Ruby 2.3 on :ubuntu:ubuntu16.04"
  command: docker build -f ./2.3/ubuntu16.04/Dockerfile .
- name: ":ruby:Ruby 2.3 on :ubuntu:ubuntu14.04"
  command: docker build -f ./2.3/ubuntu14.04/Dockerfile .
- name: ":ruby:Ruby 2.5 on :ubuntu:ubuntu18.04"
  command: docker build -f ./2.5/ubuntu18.04/Dockerfile .
- name: ":ruby:Ruby 2.5 on :ubuntu:ubuntu16.04"
  command: docker build -f ./2.5/ubuntu16.04/Dockerfile .
- name: ":ruby:Ruby 2.5 on :ubuntu:ubuntu14.04"
  command: docker build -f ./2.5/ubuntu14.04/Dockerfile .
